import * as vscode from 'vscode';
import { createOpenAIClient, ChatMessage } from '../llm/openaiClient';
import { readLlmConfig } from '../config/llmConfig';
import { CopilotDispatcher, MemoryEntry, PromptPayload } from '../copilotDispatcher';

/**
 * Execution context for tracking LLM interactions
 */
export interface ExecutionContext {
  taskId: string;
  agentName: string;
  startTime: number;
  memoryEntries: MemoryEntry[];
  promptPayload?: PromptPayload;
  responseText?: string;
  error?: string;
  endTime?: number;
}

/**
 * Execute an LLM task by:
 * 1. Composing a prompt from the task and context
 * 2. Sending it to the configured LLM endpoint
 * 3. Tracking the interaction for memory/history
 */
export async function executeLlmCommand(): Promise<void> {
  const quickPick = await vscode.window.showQuickPick(
    ['Select Task', 'Cancel'],
    { placeHolder: 'Choose an option to execute LLM task' }
  );

  if (!quickPick || quickPick === 'Cancel') {
    return;
  }

  // Get task ID from user
  const taskId = await vscode.window.showInputBox({
    prompt: 'Enter task ID (e.g., TASK-mk530r89-86665)',
    placeHolder: 'TASK-...',
    ignoreFocusOut: true,
  });

  if (!taskId) {
    return;
  }

  // Get agent name
  const agentName = await vscode.window.showInputBox({
    prompt: 'Enter agent name (coder, planner, tester)',
    value: 'coder',
    placeHolder: 'coder',
    ignoreFocusOut: true,
  });

  if (!agentName) {
    return;
  }

  // Check LLM configuration
  const configState = readLlmConfig();
  if (!configState.isConfigured) {
    void vscode.window.showErrorMessage(`LLM configuration is incomplete: ${configState.issues.join('; ')}`);
    return;
  }

  // Show progress
  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `Executing task ${taskId} with ${agentName}...`,
      cancellable: false,
    },
    async (progress) => {
      try {
        progress.report({ message: 'Composing prompt...' });

        // Compose prompt from task
        const dispatcher = new CopilotDispatcher();
        const payload = await dispatcher.composePrompt(taskId, {
          agentName,
          extraInstructions: 'Generate a detailed analysis and implementation plan.',
        });

        progress.report({ message: 'Sending to LLM...' });

        // Send to LLM
        const client = createOpenAIClient(configState.config);
        const response = await client.sendChat(payload.messages, {
          temperature: configState.config.temperature,
          timeoutMs: configState.config.timeoutMs,
        });

        // Extract response text
        const responseText =
          response.choices?.[0]?.message?.content || '(no response content)';

        progress.report({ message: 'Processing response...' });

        // Show result
        await showExecutionResult({
          taskId,
          agentName,
          prompt: payload,
          response: responseText,
          config: configState.config,
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        void vscode.window.showErrorMessage(`Task execution failed: ${message}`);
      }
    }
  );
}

/**
 * Display execution result in a new editor
 */
async function showExecutionResult(options: {
  taskId: string;
  agentName: string;
  prompt: PromptPayload;
  response: string;
  config: any;
}): Promise<void> {
  const { taskId, agentName, prompt, response } = options;

  const output = [
    '# LLM Execution Result',
    ``,
    `**Task ID:** ${taskId}`,
    `**Agent:** ${agentName}`,
    `**Timestamp:** ${new Date().toISOString()}`,
    ``,
    `## Task`,
    `- Title: ${prompt.task.title}`,
    `- Priority: ${prompt.task.priority}`,
    `- Status: ${prompt.task.status}`,
    `- Dependencies: ${prompt.task.dependencies?.length ? prompt.task.dependencies.join(', ') : 'none'}`,
    ``,
    `## Prompt Composition`,
    `- System message: ${prompt.messages[0]?.content?.slice(0, 80) || '(empty)'}...`,
    `- User message length: ${prompt.messages[1]?.content?.length || 0} chars`,
    `- Context files: ${prompt.context.files.length}`,
    `- Memory entries: ${prompt.memory.length}`,
    ``,
    `## LLM Response`,
    response,
    ``,
    `---`,
    `_Generated by Copilot Orchestrator_`,
  ].join('\n');

  const doc = await vscode.workspace.openTextDocument({
    content: output,
    language: 'markdown',
  });

  await vscode.window.showTextDocument(doc, vscode.ViewColumn.One);
  void vscode.window.showInformationMessage(`Task execution completed for ${taskId}`);
}

/**
 * Execute LLM task with streaming responses
 * Provides real-time output display with progress indicators and stream controls
 */
export async function executeLlmCommandStreaming(): Promise<void> {
  // Get task ID from user
  const taskId = await vscode.window.showInputBox({
    prompt: 'Enter task ID (e.g., TASK-mk530r89-86665)',
    placeHolder: 'TASK-...',
    ignoreFocusOut: true,
  });

  if (!taskId) {
    return;
  }

  // Get agent name
  const agentName = await vscode.window.showInputBox({
    prompt: 'Enter agent name (coder, planner, tester)',
    value: 'coder',
    placeHolder: 'coder',
    ignoreFocusOut: true,
  });

  if (!agentName) {
    return;
  }

  // Check LLM configuration
  const configState = readLlmConfig();
  if (!configState.isConfigured) {
    void vscode.window.showErrorMessage(`LLM configuration is incomplete: ${configState.issues.join('; ')}`);
    return;
  }

  // Create streaming output channel
  const { getStreamingOutputChannel } = await import('../ui/streamingOutputChannel.js');
  const outputChannel = getStreamingOutputChannel();

  // Show progress with cancellation support
  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `Streaming task ${taskId}...`,
      cancellable: true,
    },
    async (progress, cancellationToken) => {
      try {
        progress.report({ message: 'Composing prompt...' });

        // Compose prompt from task
        const dispatcher = new CopilotDispatcher();
        const payload = await dispatcher.composePrompt(taskId, {
          agentName,
          extraInstructions: 'Generate a detailed analysis and implementation plan.',
        });

        progress.report({ message: 'Starting stream...' });

        // Start streaming output
        outputChannel.startStream(taskId, agentName);

        // Create streaming client
        const { createStreamingClient } = await import('../services/streamingClient.js');
        const streamingClient = createStreamingClient(configState.config);

        // Execute streaming request
        let previousProgress = 0;
        await streamingClient.streamChat(
          payload.messages,
          {
            onChunk: (chunk: any) => {
              if (chunk.type === 'text' && chunk.content) {
                // Append to output channel
                outputChannel.appendChunk(chunk.content);
              } else if (chunk.type === 'progress' && chunk.progress !== undefined) {
                // Update progress indicator
                outputChannel.updateProgress(chunk.progress);
                const increment = chunk.progress - previousProgress;
                previousProgress = chunk.progress;
                progress.report({
                  message: `Streaming... ${chunk.progress}%`,
                  increment: increment > 0 ? increment : undefined
                });
              } else if (chunk.type === 'error' && chunk.error) {
                // Handle error chunk
                const error = new Error(chunk.error);
                outputChannel.showError(error);
              } else if (chunk.type === 'done') {
                // Stream completed
                progress.report({ message: 'Stream completed' });
              }
            },
            onComplete: (response: any) => {
              outputChannel.endStream(true);
              void vscode.window.showInformationMessage(
                `Streaming completed for ${taskId}. Check output channel for full response.`
              );
            },
            onError: (error: any) => {
              outputChannel.showError(error);
              outputChannel.endStream(false);
              void vscode.window.showErrorMessage(`Streaming failed: ${error.message}`);
            },
            onCancel: () => {
              outputChannel.endStream(false);
              void vscode.window.showWarningMessage('Streaming cancelled by user');
            },
          },
          {
            temperature: configState.config.temperature,
            timeoutMs: configState.config.timeoutMs,
            cancellationToken,
          }
        );

      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        outputChannel.showError(error instanceof Error ? error : new Error(message));
        outputChannel.endStream(false);
        void vscode.window.showErrorMessage(`Streaming execution failed: ${message}`);
      }
    }
  );
}
