/**
 * Q4Test Jest Adapter
 * 
 * Bridges Q4Test (AI Test Generator) with Jest test runner.
 * Provides utilities to:
 * - Format Q4Test generated tests for Jest compatibility
 * - Mock VSCode extension APIs
 * - Validate test generation compliance
 * - Generate test diagnostics
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Q4Test generation configuration
 */
export interface Q4TestConfig {
  projectName: string;
  testFramework: 'jest' | 'mocha' | 'vitest';
  autoValidateTests: boolean;
  maxFixAttempts: number;
  testCommand: string;
  testDirectory: string;
  generatedTestPrefix: string;
  coverageThreshold: {
    branches: number;
    functions: number;
    lines: number;
    statements: number;
  };
}

/**
 * Test scenario category from Q4Test AI analysis
 */
export interface TestScenario {
  category: 'critical' | 'logical' | 'error' | 'edge';
  description: string;
  testName: string;
  expectedBehavior: string;
  inputData?: Record<string, unknown>;
  expectedOutput?: unknown;
  shouldThrow?: boolean;
  priority: 'high' | 'medium' | 'low';
}

/**
 * Generated test metadata
 */
export interface GeneratedTestMetadata {
  sourceFile: string;
  generatedAt: Date;
  scenarios: TestScenario[];
  q4testVersion: string;
  jestVersion: string;
  estimatedCoverage: number;
}

/**
 * Jest test template generator for Q4Test scenarios
 */
export class Q4TestJestAdapter {
  private config: Q4TestConfig;
  private metadata: Map<string, GeneratedTestMetadata> = new Map();

  constructor(configPath: string = '.q4testrc.json') {
    const configContent = fs.readFileSync(
      path.resolve(configPath),
      'utf-8'
    );
    this.config = JSON.parse(configContent);
  }

  /**
   * Generate Jest test template from Q4Test scenarios
   */
  generateTestTemplate(
    sourceFilePath: string,
    scenarios: TestScenario[],
    fileBeingTested: string
  ): string {
    const fileName = path.basename(fileBeingTested);
    const moduleName = fileName.replace(/\.(ts|js)$/, '');
    const testFileName = `${this.config.generatedTestPrefix}${moduleName}.test.ts`;

    let template = `/**
 * AUTO-GENERATED TEST SUITE BY Q4TEST
 * 
 * Source File: ${fileBeingTested}
 * Generated By: Q4Test AI Test Generator
 * Test Framework: Jest
 * Generated At: ${new Date().toISOString()}
 * 
 * This test suite was AI-generated based on code analysis.
 * Please review and adjust mocks/assertions as needed for your use case.
 * 
 * Run with: npm run test:jest -- --testNamePattern="${this.config.generatedTestPrefix}"
 */

import { describe, it, expect, beforeEach, afterEach, jest } from '@jest/globals';

// Mock VSCode API
jest.mock('vscode', () => ({
  Uri: {
    file: jest.fn((path: string) => ({ fsPath: path })),
    parse: jest.fn(),
  },
  window: {
    showErrorMessage: jest.fn(),
    showInformationMessage: jest.fn(),
    showWarningMessage: jest.fn(),
    showInputBox: jest.fn(),
    showQuickPick: jest.fn(),
    showOpenDialog: jest.fn(),
    showSaveDialog: jest.fn(),
  },
  workspace: {
    openTextDocument: jest.fn(),
    workspaceFolders: [],
    onDidChangeConfiguration: jest.fn(() => ({ dispose: jest.fn() })),
  },
  commands: {
    registerCommand: jest.fn(),
    executeCommand: jest.fn(),
  },
  ExtensionContext: jest.fn(),
}), { virtual: true });

// Import module under test
import * as moduleUnderTest from '${this.getRelativeImportPath(sourceFilePath)}';

describe('${moduleName}', () => {
  // Test-wide setup
  beforeEach(() => {
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

`;

    // Add test cases organized by category
    const categorizedScenarios = this.groupScenariosByCategory(scenarios);

    for (const [category, categoryScenarios] of Object.entries(categorizedScenarios)) {
      template += `\n  // ========== ${category.toUpperCase()} TESTS ==========\n`;
      
      for (const scenario of categoryScenarios) {
        template += this.generateTestCase(scenario);
      }
    }

    template += `\n});\n`;

    return template;
  }

  /**
   * Generate individual Jest test case from scenario
   */
  private generateTestCase(scenario: TestScenario): string {
    const priorityMarker = scenario.priority === 'high' ? '🔴' : 
                          scenario.priority === 'medium' ? '🟡' : '🟢';

    let testCase = `
  it('${priorityMarker} [${scenario.category.toUpperCase()}] ${scenario.testName}', async () => {
    // Test scenario: ${scenario.description}
    // Expected behavior: ${scenario.expectedBehavior}
    
`;

    if (scenario.inputData) {
      testCase += `    // Arrange\n`;
      testCase += `    const testData = ${JSON.stringify(scenario.inputData, null(2 as unknown as number), 4)};\n`;
    }

    testCase += `    // Act\n`;
    testCase += `    // TODO: Replace with actual function call\n`;
    testCase += `    // const result = await moduleUnderTest.functionName(testData);\n`;

    if (scenario.shouldThrow) {
      testCase += `\n    // Assert\n`;
      testCase += `    expect(() => {\n`;
      testCase += `      // Function should throw\n`;
      testCase += `    }).toThrow();\n`;
    } else if (scenario.expectedOutput !== undefined) {
      testCase += `\n    // Assert\n`;
      testCase += `    expect(result).toEqual(${JSON.stringify(scenario.expectedOutput)});\n`;
    } else {
      testCase += `\n    // Assert\n`;
      testCase += `    expect(true).toBe(true); // TODO: Add assertions\n`;
    }

    testCase += `  });\n`;

    return testCase;
  }

  /**
   * Group scenarios by category
   */
  private groupScenariosByCategory(
    scenarios: TestScenario[]
  ): Record<string, TestScenario[]> {
    const grouped: Record<string, TestScenario[]> = {
      critical: [],
      logical: [],
      error: [],
      edge: []
    };

    for (const scenario of scenarios) {
      grouped[scenario.category].push(scenario);
    }

    return grouped;
  }

  /**
   * Generate relative import path from source file
   */
  private getRelativeImportPath(sourceFile: string): string {
    // Convert C:\path\to\file.ts to ../path/to/file
    const normalized = sourceFile
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '');
    
    return normalized.startsWith('../') ? normalized : `./${normalized}`;
  }

  /**
   * Validate generated test compliance with Jest/TypeScript
   */
  validateGeneratedTest(testFilePath: string): {
    valid: boolean;
    errors: string[];
    warnings: string[];
  } {
    const errors: string[] = [];
    const warnings: string[] = [];

    try {
      const content = fs.readFileSync(testFilePath, 'utf-8');

      // Check Jest imports
      if (!content.includes('import') && !content.includes('describe')) {
        errors.push('Missing Jest imports or describe block');
      }

      // Check describe blocks
      if (!content.includes('describe(')) {
        errors.push('Missing describe() block - required for Jest');
      }

      // Check test cases
      if (!content.includes('it(') && !content.includes('test(')) {
        warnings.push('No test cases found - only describe block structure exists');
      }

      // Check assertions
      if (!content.includes('expect(')) {
        warnings.push('No assertions found - tests may be incomplete');
      }

      // Check for VSCode API mocks
      if (!content.includes('jest.mock(')) {
        warnings.push('No jest.mock() calls - ensure VSCode APIs are properly mocked');
      }

      // Check TypeScript types
      if (!content.includes(': ') && !content.includes('<')) {
        warnings.push('Few type annotations detected - consider adding for better type safety');
      }

      return {
        valid: errors.length === 0,
        errors,
        warnings
      };
    } catch (error) {
      errors.push(`Failed to validate file: ${error instanceof Error ? error.message : String(error)}`);
      return { valid: false, errors, warnings };
    }
  }

  /**
   * Generate npm scripts for Q4Test workflows
   */
  generateNpmScripts(): Record<string, string> {
    return {
      'test:q4test': 'jest --config jest-q4test.config.js',
      'test:q4test:watch': 'jest --config jest-q4test.config.js --watch',
      'test:q4test:coverage': 'jest --config jest-q4test.config.js --coverage',
      'test:q4test:debug': 'node --inspect-brk ./node_modules/jest/bin/jest.js --config jest-q4test.config.js',
      'q4test:validate': 'node scripts/validate-q4test.js',
      'q4test:merge-coverage': 'node scripts/merge-coverage.js'
    };
  }

  /**
   * Track generated test metadata
   */
  trackGeneration(
    sourceFile: string,
    scenarios: TestScenario[],
    q4testVersion: string = '1.0.5',
    jestVersion: string = '29.0.0'
  ): void {
    const metadata: GeneratedTestMetadata = {
      sourceFile,
      generatedAt: new Date(),
      scenarios,
      q4testVersion,
      jestVersion,
      estimatedCoverage: this.estimateCoverage(scenarios)
    };

    this.metadata.set(sourceFile, metadata);
  }

  /**
   * Estimate coverage from scenarios
   */
  private estimateCoverage(scenarios: TestScenario[]): number {
    // Basic estimation: critical=30%, logical=40%, error=20%, edge=10%
    let total = 0;
    const weights: Record<string, number> = {
      critical: 0.30,
      logical: 0.40,
      error: 0.20,
      edge: 0.10
    };

    for (const scenario of scenarios) {
      total += weights[scenario.category] || 0;
    }

    return Math.min(Math.round(total * 100), 100);
  }

  /**
   * Get generation diagnostics
   */
  getDiagnostics(): Map<string, GeneratedTestMetadata> {
    return this.metadata;
  }

  /**
   * Generate coverage report summary
   */
  generateCoverageSummary(): string {
    let summary = '# Q4Test Generated Test Coverage Summary\n\n';
    summary += `Generated ${this.metadata.size} test suites\n\n`;

    let totalEstimatedCoverage = 0;
    for (const metadata of this.metadata.values()) {
      summary += `- ${metadata.sourceFile}: ${metadata.estimatedCoverage}% (${metadata.scenarios.length} scenarios)\n`;
      totalEstimatedCoverage += metadata.estimatedCoverage;
    }

    if (this.metadata.size > 0) {
      const avgCoverage = Math.round(totalEstimatedCoverage / this.metadata.size);
      summary += `\n**Average Estimated Coverage: ${avgCoverage}%**\n`;
    }

    return summary;
  }
}

// Export for use in npm scripts and Jest setup
export default Q4TestJestAdapter;
